on:
  push:
    branches: [ master ]

name: Deploy to AWS

jobs:
  lambda-decode-verify-jwt:
    name: "Deploy Lambda decode-verify-jwt"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/zip-lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_Access_Key_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_Secret_Access_Key }}
        AWS_REGION: 'us-east-1'
        LAMBDA_DIRECTORY: 'Lambda/decode-verify-jwt'

  s3-busy-bee-app:
    name: "Deploy Static busy-bee.app Website"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy-s3
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_Access_Key_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_Secret_Access_Key }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'S3/busy-bee.app'
        AWS_S3_BUCKET: 'busy-bee.app'
    